'use strict';

const seedAuthors = [
  {
    name: 'Nguyễn Minh Đức',
    bio_vi: 'Biên tập viên cao cấp với 8 năm kinh nghiệm lái thử và đánh giá xe tại Việt Nam và quốc tế.',
    bio_en: 'Senior editor with 8 years of car testing and reviewing experience in Vietnam and internationally.',
    role: 'journalist',
  },
  {
    name: 'Trần Quốc Bảo',
    bio_vi: 'Nhà báo xe hơi chuyên về thị trường xe Nhật và Hàn tại Việt Nam.',
    bio_en: 'Automotive journalist specializing in Japanese and Korean cars in Vietnam.',
    role: 'journalist',
  },
  {
    name: 'Lê Hoàng Nam',
    bio_vi: 'Tổng biên tập, chuyên gia phân tích thị trường ô tô Việt Nam hơn 10 năm.',
    bio_en: 'Editor-in-chief, expert analyst with over 10 years in the Vietnamese automotive market.',
    role: 'editor',
  },
];

const seedCarBrands = [
  { name_vi: 'Toyota', name_en: 'Toyota', slug: 'toyota', flag_emoji: '🇯🇵', country_of_origin: 'Japan', display_order: 1 },
  { name_vi: 'Honda', name_en: 'Honda', slug: 'honda', flag_emoji: '🇯🇵', country_of_origin: 'Japan', display_order: 2 },
  { name_vi: 'VinFast', name_en: 'VinFast', slug: 'vinfast', flag_emoji: '🇻🇳', country_of_origin: 'Vietnam', display_order: 3 },
  { name_vi: 'Hyundai', name_en: 'Hyundai', slug: 'hyundai', flag_emoji: '🇰🇷', country_of_origin: 'South Korea', display_order: 4 },
  { name_vi: 'Mazda', name_en: 'Mazda', slug: 'mazda', flag_emoji: '🇯🇵', country_of_origin: 'Japan', display_order: 5 },
  { name_vi: 'Kia', name_en: 'Kia', slug: 'kia', flag_emoji: '🇰🇷', country_of_origin: 'South Korea', display_order: 6 },
  { name_vi: 'Mercedes-Benz', name_en: 'Mercedes-Benz', slug: 'mercedes-benz', flag_emoji: '🇩🇪', country_of_origin: 'Germany', display_order: 7 },
  { name_vi: 'BMW', name_en: 'BMW', slug: 'bmw', flag_emoji: '🇩🇪', country_of_origin: 'Germany', display_order: 8 },
];

const seedCarModels = [
  {
    brandSlug: 'vinfast',
    name: 'VF 9',
    slug: 'vf-9',
    segment: 'suv',
    body_type: 'SUV 3 hàng ghế',
    year_from: 2023,
    price_from: 1890000000,
    price_to: 2090000000,
    status: 'on_sale',
    description_vi: 'SUV điện 7 chỗ hạng sang của VinFast, cạnh tranh với các mẫu SUV điện cao cấp toàn cầu.',
    description_en: "VinFast's flagship 7-seat electric SUV, competing with global premium electric SUVs.",
    our_rating: 9.0,
  },
  {
    brandSlug: 'vinfast',
    name: 'VF 8',
    slug: 'vf-8',
    segment: 'suv',
    body_type: 'SUV 5 chỗ',
    year_from: 2022,
    price_from: 1057000000,
    price_to: 1219000000,
    status: 'on_sale',
    description_vi: 'SUV điện 5 chỗ tầm trung của VinFast, best-seller trong phân khúc xe điện Việt Nam.',
    description_en: "VinFast's mid-range 5-seat electric SUV, best-seller in Vietnam's EV segment.",
    our_rating: 8.2,
  },
  {
    brandSlug: 'toyota',
    name: 'Camry',
    slug: 'camry',
    segment: 'sedan',
    body_type: 'Sedan hạng D',
    year_from: 2024,
    price_from: 1235000000,
    price_to: 1455000000,
    status: 'on_sale',
    description_vi: 'Sedan hạng D bán chạy nhất phân khúc tại Việt Nam, biểu tượng của sự tin cậy.',
    description_en: "Best-selling D-segment sedan in Vietnam, a symbol of reliability.",
    our_rating: 8.0,
  },
  {
    brandSlug: 'honda',
    name: 'Civic',
    slug: 'civic',
    segment: 'sedan',
    body_type: 'Sedan hạng C',
    year_from: 2022,
    price_from: 730000000,
    price_to: 870000000,
    status: 'on_sale',
    description_vi: 'Sedan hạng C thể thao hàng đầu của Honda, được giới trẻ yêu thích.',
    description_en: "Honda's leading sporty C-segment sedan, popular with younger buyers.",
    our_rating: 7.5,
  },
  {
    brandSlug: 'mazda',
    name: 'CX-5',
    slug: 'cx-5',
    segment: 'suv',
    body_type: 'SUV 5 chỗ',
    year_from: 2022,
    price_from: 759000000,
    price_to: 969000000,
    status: 'on_sale',
    description_vi: 'SUV crossover cao cấp nhất phân khúc tầm trung, nổi tiếng với thiết kế đẹp và vận hành tốt.',
    description_en: 'The most premium mid-range crossover SUV, known for beautiful design and driving dynamics.',
    our_rating: 8.5,
  },
  {
    brandSlug: 'hyundai',
    name: 'Santa Fe',
    slug: 'santa-fe',
    segment: 'suv',
    body_type: 'SUV 7 chỗ',
    year_from: 2024,
    price_from: 1080000000,
    price_to: 1380000000,
    status: 'on_sale',
    description_vi: 'SUV 7 chỗ flagship của Hyundai tại Việt Nam với nhiều công nghệ hiện đại.',
    description_en: "Hyundai's flagship 7-seat SUV in Vietnam with extensive modern technology.",
    our_rating: 8.3,
  },
];

module.exports = { seedAuthors, seedCarBrands, seedCarModels };
